Fix the missing deps issue from the bash script.
arcticicestudio/nord-gnome-terminal pull request #41
Opened 2023-03-16 00:45 UTC by dsmithhayes

2023-03-18 10:47 UTC, svengreb requested changes
Hi @dsmithhayes :wave:, thanks for your contribution :+1:
I've added some small suggestions, but otherwise this is the fix I've also mentioned in #40 💪

2023-03-18 10:47 UTC, svengreb commented on src/nord.sh
> +  declare -a missing_deps=()
Let's assign the value separately which is safer for Bash.

```suggestion
  declare -a missing_deps deps
  deps=("${!1}")
  missing_deps=()
```

2023-03-18 10:47 UTC, svengreb commented on src/nord.sh
> +  if [ "${#missing_deps[*]}" -eq 0 ]; then
This can lead to problems for the iterator values so let's revert this.

```suggestion
  if [ ${#missing_deps[*]} -eq 0 ]; then
```

2023-03-26 23:32 UTC, dsmithhayes commented
Hello @svengreb, I apologize for the late response, but I have made the requested changes.

2023-03-29 21:19 UTC, svengreb approved these changes
@dsmithhayes There's no need for an apology, you don't owe anyone anything in open source since anyone spend free time 😉
Thanks for updating the changes, this looks good to me 🚀

2023-03-29 21:27 UTC, merged